[profile.default]
solc_version = '0.8.28'
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 10000
# @see {@link https://github.com/foundry-rs/foundry/issues/4060}
auto_detect_remappings = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = true
via_ir = true

[lint]
exclude_lints = ["unsafe-typecast", "unaliased-plain-import", "mixed-case-variable", "mixed-case-function", "asm-keccak256", "pascal-case-struct", "screaming-snake-case-immutable", "incorrect-shift"]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

[fmt]
sort_imports = true